id: A4224955C
title: 'Opening the Door to Great Bliss: An Aspiration Towards the Realm of Abhirati'
type: translation
pechas:
- I2C5445BD
- I2F2AA79D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:17.193258
  last_modified_at: 2023-01-04 12:07:17.193263
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I2C5445BD/9954: DB70
  I2F2AA79D/1A1F: DB70
